### ISSUE TITLE
Can't add integration to HA addon's.

### ISSUE THREAD

**Issue by Puntoboy** [gndean/home-assistant-hypervolt-charger#1]
Just posting here to keep it all in one place, Facebook can be messy for tracking issues. Just in case it's not me doing something wrong. :)

I added the integration to HACS yesterday. Rebooted HA, attempted to add the integration but it doesn't show in the list. 

![image](https://user-images.githubusercontent.com/11718878/207835235-c0a3d77f-31b2-48d3-89a5-679e5449a69a.png)

I've tried:

1. Logging out
2. Browser cache delete
3. New browser that I haven't used to login to HA before
4. Several reboots of HA
5. Tried the HA app on my iPhone

Nothing seems to work. 

I'm running HA 2022.9.4, not sure if that makes a difference. I don't like upgrading HA that often as it can cause more issues than it solves.

**Comment by gndean** [comment]
Thanks for the feedback. I'm in the process of publishing to HACS. I wonder if once the extension is in the HACS store, this might change. So let's leave this issue open until that's been done then revisit.

**Comment by n0rbie** [comment]
Thanks for creating this - I’m eagerly waiting to install it via HACS, but it doesn’t yet appear as an option. Following to find out when it’s been added to the store!

**Comment by Puntoboy** [comment]
> Thanks for creating this - I’m eagerly waiting to install it via HACS, but it doesn’t yet appear as an option. Following to find out when it’s been added to the store!

Normally, you would just add this as a custom repository, then it will appear for you to install.

**Comment by n0rbie** [comment]
> > Thanks for creating this - I’m eagerly waiting to install it via HACS, but it doesn’t yet appear as an option. Following to find out when it’s been added to the store!
> 
> Normally, you would just add this as a custom repository, then it will appear for you to install.

I hadn’t realised that, thanks! I’ve added it as a custom repository, downloaded it, and I was able to add the integration in HA. Latest version here.

![519FFBDA-6912-4FDE-9ABC-74A8733A70BD](https://user-images.githubusercontent.com/20725002/207952429-f4062b2f-2d6a-4db7-b954-2898a24cfe52.jpeg)

**Comment by Puntoboy** [comment]
Awesome, glad that worked for you :) 

What version of HA are you on?

**Comment by n0rbie** [comment]
Home Assistant 2022.12.6
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.0 - latest
RaspberryPi 4

**Comment by Puntoboy** [comment]
Yeah newer than mine, I wonder if that's the issue.

**Comment by exalyte** [comment]
open HA goto HACs click the 3 dots in the right corner and add a new customer repository 
![image](https://user-images.githubusercontent.com/73583564/207983897-96a8471f-b2e5-4641-a274-1ea07efbef56.png)


paste
github.com/gndean/home-assistant-hypervolt-charger
![image](https://user-images.githubusercontent.com/73583564/207983983-650f43d9-2294-4541-be91-2df6ed893971.png)

type is integration 

it will then appear when you search for it 

Hope that helps!

**Comment by Puntoboy** [comment]
> open HA goto HACs click the 3 dots in the right corner and add a new customer repository ![image](https://user-images.githubusercontent.com/73583564/207983897-96a8471f-b2e5-4641-a274-1ea07efbef56.png)
> 
> paste github.com/gndean/home-assistant-hypervolt-charger ![image](https://user-images.githubusercontent.com/73583564/207983983-650f43d9-2294-4541-be91-2df6ed893971.png)
> 
> type is integration
> 
> it will then appear when you search for it ![image](https://user-images.githubusercontent.com/73583564/207984073-d0f73d3a-beda-4013-a0ac-31fb34102f0f.png)
> 
> Hope that helps!

I think you missed the bit where I've done that :)

**Comment by exalyte** [comment]
> 
> I think you missed the bit where I've done that :)

Oh dang sorry! well least its fixed :)

**Comment by Puntoboy** [comment]
> > I think you missed the bit where I've done that :)
> 
> Oh dang sorry! well least its fixed :)

No, afraid it's not. That's my issue. I added the repository first, but when I go to the integrations page in HA it doesn't show up.

**Comment by exalyte** [comment]
> > > I think you missed the bit where I've done that :)
> > 
> > 
> > Oh dang sorry! well least its fixed :)
> 
> No, afraid it's not. That's my issue. I added the repository first, but when I go to the integrations page in HA it doesn't show up.

Oh i see, if you go to add the repository again ( https://github.com/gndean/home-assistant-hypervolt-charger ) does it say its already added? 
![image](https://user-images.githubusercontent.com/73583564/207987575-6f967ab3-fda7-4ded-a28c-777b340b5582.png)

ive had that a few times with HACs, did you try the big button bottom right 

![image](https://user-images.githubusercontent.com/73583564/207987307-72fc3428-2089-4744-a28c-09dea742463a.png)
to search for repository rather than the search bar at the top?

**Comment by Puntoboy** [comment]
Yep and yet. I can see this error in the logs, so it is loading it from HACS, I just can't see it. 

![image](https://user-images.githubusercontent.com/11718878/207987785-e3589fad-8145-4075-85a4-85489744161d.png)

**Comment by exalyte** [comment]
> OK, this is now saying update. But it appears to be the same version? It wasn't saying update before.
> 
> ![image](https://user-images.githubusercontent.com/11718878/207987931-6a2e4433-dc59-4022-b3d8-3ff3f6e12b7d.png)

Give it a shot, the auth released v1.0.1 a few hours ago perhaps itll resolve your issue.

**Comment by Puntoboy** [comment]
Rebooting now

**Comment by Puntoboy** [comment]
Nope, still not there. 

![image](https://user-images.githubusercontent.com/11718878/207988277-60cf14e5-4659-45ae-a1ed-6ee323e7feb4.png)

**Comment by exalyte** [comment]
very odd, go back to HACs and search for hypervolt 
then redownload
![image](https://user-images.githubusercontent.com/73583564/207988379-bcdee589-b2db-46e3-b028-fafba06c7e67.png)


Im on 2022.12.6 btw perhaps you need to goto a newer version of HA (you can choose your version via command line just SSH into your HA box and run the following command 
`ha core update --version 2022.11.5 --backup` for nov update 5 etc. but 12.6 so far hasnt caused any issues for me.

**Comment by Puntoboy** [comment]
Updating HA to the latest version seems to have fixed it. :)
