### ISSUE TITLE
Data no longer being displayed

### ISSUE THREAD

**Issue by boab21mac** [gndean/home-assistant-hypervolt-charger#10]
Since a unit firmware upgrade, there is no data being displayed within the apo![image](https://user-images.githubusercontent.com/120062210/209766139-604f155b-ee52-450c-b5e1-0a519fc72099.png)

**Comment by exalyte** [comment]
This is known info here: 
https://github.com/gndean/home-assistant-hypervolt-charger/issues/9#issuecomment-1365146847

**Comment by gndean** [comment]
Thanks for the feedback.
As above, https://github.com/gndean/home-assistant-hypervolt-charger/issues/9 will track this
