### ISSUE TITLE
CT current used for home energy monitoring

### ISSUE THREAD

**Issue by brickpunk** [gndean/home-assistant-hypervolt-charger#11]
I've just made the connection that the CT could be used to monitor energy consumption for the whole property, however when I try to select the sensor in the energy tab it doesn't show and provides this link as a solution

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

It would be a really useful benefit to be able to track this, hoping it's an easy thing to implement, great work on this integration!

**Comment by Kahn** [comment]
A workaround likely similar to mine for session energy total prior to the new sensor is adding a `utility meter` helper then attaching it to the CT power and reset it daily. Try this

![image](https://user-images.githubusercontent.com/8662/210031015-5ce42fcc-d540-4e11-a6f2-f49382ee6964.png)

I haven't used a sensor with the delta need before since I get my solar PV data from the SolarEdge meter with separate imports and exports but this should handle positive and negative values.

**Comment by brickpunk** [comment]
Thanks for the reply, I don't think my idea will work anyway, I've just noticed it's stopped reporting the CT values once the car has stopped charging!

**Comment by BadgerLoaf** [comment]
> Thanks for the reply, first I need to sort out my intermittent wifi issues, all working when I went to bed but dropped out 5 hours ago

@brickpunk - as suggested in your first edit, the Hypervolt only monitors the CT Clamp when in use, so unfortunately it can't be used to monitor house usage.

Otherwise, the Utility Meter suggested by @Kahn would have been perfect - I used that for my water monitoring.

**Comment by gndean** [comment]
As @BadgerLoaf says, the CT sensors only report while charging so are no good for general energy tracking.
For tracking the energy usage of just the Hypervolt charger, you can use the Hypervolt Session Energy Total Increasing sensor.

**Comment by stingray75** [comment]
Do the CT sensors report with HV 3.0 chargers, as I don't see any CT information, even while charging? I called Hypervolt and they said they see readings, so my clamp is working.

**Comment by stingray75** [comment]
Does this feature work with a HV 3.0 charger, as I don't see any CT information, even while charging? I called Hypervolt and they said they see readings, so my clamp is working.Does this feature work with a HV 3.0 charger, as I don't see any CT information, even while charging? I called Hypervolt and they said they see readings, so my clamp is working.

**Comment by gndean** [comment]
It looks like 3.0 chargers don't report the CT data, nor the voltage. At least not in the same way.
Sorry, I have no way of testing this as I don't have a 3.0 device.

**Comment by gtb08177** [comment]
For my hypervolt home 3 pro charger - I see the grid power fluctuate even when not charging the car.

Is this thread specifically saying for older gen's it was no good but now with newer it's good for energy reporting? I've based my whole home energy on this
