### ISSUE TITLE
Feature Request: Sensor detecting if the charger is plugged into a car

### ISSUE THREAD

**Issue by BadgerLoaf** [gndean/home-assistant-hypervolt-charger#12]
I suspect this isn't available from the Hypervolt, but just incase.... 

Is there anyway to have a sensor that detects if the cable is plugged into a car (for instance if the charging has manually been stopped, or if its only using solar excess and there isn't enough sun)

Thanks!

**Comment by gndean** [comment]
I don't think this is possible. There doesn't appear to be a flag to indicate the plugged status available via the APIs.
