### ISSUE TITLE
Failed To Connect

### ISSUE THREAD

**Issue by emmet02** [gndean/home-assistant-hypervolt-charger#13]
Issues appeared in my log today regarding configuration 
<img width="460" alt="2023-01-07 14_32_35-Settings – Home Assistant" src="https://user-images.githubusercontent.com/10803258/211155881-2703b192-5978-4729-b371-c5ae162579ae.png">

I couldn't figure out what I needed to change, so went for the old "delete and start again", however on removal and re-install, my connection is not getting auth'd.

<img width="447" alt="2023-01-07 14_32_01-Settings – Home Assistant" src="https://user-images.githubusercontent.com/10803258/211155879-1d9a7a81-123b-4f10-b005-b71930d230f7.png">

Same credentials are logging into the site @ www.hypervolt.co.uk without any hassle.

Any ideas? Are we blocked again?

**Comment by gndean** [comment]
Thanks for reporting. Yes sorry, blocked again as the extension is spamming the Hypervolt servers in some cases.
Keep updated in: https://github.com/gndean/home-assistant-hypervolt-charger/issues/9#issuecomment-1374012767
