### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by crobbins215d** [gndean/home-assistant-hypervolt-charger#2]
Hi,

Ive just installed and rebooted, when trying to logic I get Authentication Failure.

I have logged out and logged in the app with the username and password. (Copy & Pasted)
I have also logged in with the same username and password at https://hypervolt.co.uk/dashboard
![image](https://user-images.githubusercontent.com/44638417/207859222-db14eb6e-50b6-450f-bc49-7830da0e7d23.png)

My email doesn't have any special characters other than @. My password is 50 characters long, so thinking that might be the issue?

**Comment by crobbins215d** [comment]
Resetting my password to 9 characters worked. I prefer auto-generated long passwords

**Comment by gndean** [comment]
Thanks for the feedback. I can repeat this with specific special characters in the password - it's not necessarily the length that causes it to fail.
Stand by for a fix. You shouldn't have to compromise your password!

**Comment by crobbins215d** [comment]
Thanks, @gndean. Thought that could also be it

**Comment by gndean** [comment]
Should be fixed in https://github.com/gndean/home-assistant-hypervolt-charger/releases/tag/v1.0.1
Give it a try and let me know

**Comment by crobbins215d** [comment]
Yep, reset my password to include special characters, and it is working correctly. Thanks
