### ISSUE TITLE
Multiple chargers not visible

### ISSUE THREAD

**Issue by albyskoons** [gndean/home-assistant-hypervolt-charger#20]
Hi
Is there a way to discover all chargers that are registered with a given HyperVolt account?

**Comment by albyskoons** [comment]
Seen that this is a limitation in this version - closing issue

**Comment by gndean** [comment]
Do you have more than one charger? I'd like to support this but have no way of testing it.

**Comment by albyskoons** [comment]
I do indeed - 2 x V2's
I can't see a way of accessing the second on the web dashboard either, although that could just be me being blind.
I have only been able to configure them with the App.

Happy to help test if I can.

Great integration by the way - I've been hoping for something like this for ages.

**Comment by gndean** [comment]
I think I might understand how to support multiple chargers - the Hypervolt API does return a list of chargers associated with the account. My intention is that, if multiple are found after logging in via the integration, you'll be able to choose which one to add. Then to add a second, you'd repeat the process in Home Assistant and choose the second.

@albyskoons , your help would be appreciated testing this.

I'll reopen this issue and have a go at implementing the above when I get chance, and ask you to give it a go.

**Comment by albyskoons** [comment]
I look forward to testing it 👍

**Comment by gndean** [comment]
@albyskoons OK, I've had a go at supporting multiple chargers. You should be prompted to select a charger serial after logging in. Repeat the Add Integration process to add the second charger.

I've released the integration as a v1.1.0 beta for now, until you're able to validate it works. You can install via HACS but will need to manually re-download the integration via the HACS UI and choose to show Beta versions.

Thanks and let me know how you get on!

**Comment by albyskoons** [comment]
I've updated to the beta version in HACS, and restarted HA, but have not removed and re-added the integration in the HA integations section. When attempting to add an additional instance, I get the following error message. Enabling debug logging gave the attached error message.
![image](https://user-images.githubusercontent.com/92802718/227797037-174c9812-8083-4055-88eb-6a0da36c681c.png)
![image](https://user-images.githubusercontent.com/92802718/227797059-a5a2d5df-c8f2-4916-a28f-14a3d24cb93c.png)

**Comment by gndean** [comment]
Thanks for trying... I now realise I hadn't actually pushed the new code before creating the release!

OK, I've released a V1.1.0 Beta 2. Can you go through the same process and try again please?

**Comment by albyskoons** [comment]
All working - thanks! When re-adding the integration, it prompts for the serial number. Apologies I didn't get a screen shot as I re-added from my mobile device.  Thanks again for building this 👍

**Comment by gndean** [comment]
That's brilliant! Thanks for confirming.
