### ISSUE TITLE
Unable to update number.hypervolt_max_current value outside of the entity card. 

### ISSUE THREAD

**Issue by Rhysgh** [gndean/home-assistant-hypervolt-charger#23]
Hi, as mentioned on FB i cant seem to update the value of number.hypervolt_max_current via any method and io cant see why. i wonder if you can/ have so that I can try and fault find this better?

**Comment by gndean** [comment]
In the FB thread, you stated that you were using Node Red. Sorry I can't help with that.

If you try plain Home Assistant, does this following work within an automation?
Add Action / Device / <choose HV device> / Set value for Hypervolt Max Current

Can you update the value via the slider in the UI (just like in my demo video here: https://github.com/gndean/home-assistant-hypervolt-charger/blob/main/demo.gif

**Comment by Rhysgh** [comment]
I can't do it on “plain home assistant” I can use the slide and do or manually yes.

iTyped with my iThumbs so please excuse any brevity.


Rhys Hill 
 Technical Manager

Email: ***@***.***  
 Tel: 02031461164
   
   
________________________________
