### ISSUE TITLE
Hypervolt v3.0 CT sensors unavailable

### ISSUE THREAD

**Issue by frazzyfin** [gndean/home-assistant-hypervolt-charger#27]
I read in a previous issue thread that the CT clamp sensors on the v3 version of the Hypervolt don't work, and indeed this is reflected in my HA instance. Do you have any documentation on the Hypervolt API and/or a Postaman environment that I can use to explore if the CT data is available? Thanks.

**Comment by gndean** [comment]
I don't have any documentation but you can see the API calls used in the code: https://github.com/gndean/home-assistant-hypervolt-charger/blob/main/custom_components/hypervolt_charger/hypervolt_api_client.py
In this case, HV have confirmed that V3.0 doesn't populate these values, as they are not used in the app.
