### ISSUE TITLE
Documentation & Known Issues links incorrect

### ISSUE THREAD

**Issue by crobbins215d** [gndean/home-assistant-hypervolt-charger#3]
Documentation and Known Issues links from the integrations menu go to deadlinks 

Going to 
https://github.com/gndean/hypervolt_charger
&
https://github.com/gndean/hypervolt_charger/issues

Instead of
https://github.com/gndean/home-assistant-hypervolt-charger
&
https://github.com/gndean/home-assistant-hypervolt-charger/issues

Thanks, just a small one, but thought I would log just in case.

**Comment by gndean** [comment]
Fixed in https://github.com/gndean/home-assistant-hypervolt-charger/releases/tag/v1.0.1
