### ISSUE TITLE
Activation Mode not

### ISSUE THREAD

**Issue by SgtHobNob** [gndean/home-assistant-hypervolt-charger#32]
Hypervolt Activation Mode isn't synchronising at all, even after hours. 

It's strange how some things are instant but this isn't, im guessing it's on Hypervolts end and not something that can be overcome. 

Thank you for your hard work.

**Comment by gndean** [comment]
Apologies for the slow reply... does this sync one way and not the other? i.e. if you change the activation mode within the HV app, the HA integration should sync within 5 minutes. However, for the other way, i.e. changing in the HA integration, I've no idea how/if the HV app resyncs to the new setting.

**Comment by SgtHobNob** [comment]
I was being impatient, apologies for not following up sooner! I thought HA wasn't updating the Hypervolt, it was it just the app wasn't showing it right away as you mention. Odd some things are instant and others aren't!

Side question though, is there a way to determine if the charger is plugged in or not? The app now reports it is/isnt plugged in. Having that in HA would be very useful!

Thanks for your hard work.
