### ISSUE TITLE
Incorrect CT Clamp Power Reading

### ISSUE THREAD

**Issue by rockclimb** [gndean/home-assistant-hypervolt-charger#33]
As of 25th September my Hypervolt 3 has started providing continuous readings from the CT Clamp, irrespective of whether I'm charging (before that the power was always zero, and the current only showed during charging). This is potentially very useful. Unfortunately it looks like the power is out by a factor of 100 though - I'm getting readings like 13.93A, 32.81W. Is there a way I can easily capture what's coming back from the API for you?

**Comment by gndean** [comment]
Thanks for the info - that's interesting.

Looking at my recent data, with my HV 2.0, I see the same thing now: About a 1/100th of the expected power. I just hadn't noticed because I don't look at that sensor but it seems to have changed around the end of Sept, matching your findings. So I guess HV have changed their API to return Watts now, rather than the 0.01W units the looked to have used when I first created the integration.

I'll look at creating a release with a fixed scale factor for this sensor.

**Comment by gndean** [comment]
I've created a new release to fix this: https://github.com/gndean/home-assistant-hypervolt-charger/releases/tag/v1.2.2

Give it a try and let me know whether it works for you.

**Comment by stoogie** [comment]
Just received this after adding new version:

Logger: homeassistant.setup
Source: setup.py:185
First occurred: 12:06:34 (1 occurrences) 
Last logged: 12:06:34

Setup failed for custom integration hypervolt_charger: Requirements for hypervolt_charger not found: ['websockets==11.0’].


---
To do is to be - Descartes
To be is to do - Voltaire
Do be do be do - Frank Sinatra

Phone: +447810770779
LinkedIn: http://j.mp/martinbrown

**Comment by stoogie** [comment]
> Just received this after adding new version: Logger: homeassistant.setup Source: setup.py:185 First occurred: 12:06:34 (1 occurrences) Last logged: 12:06:34 Setup failed for custom integration hypervolt_charger: Requirements for hypervolt_charger not found: ['websockets==11.0’].

Revered back to 1.2.1 and that version loaded OK.

**Comment by gndean** [comment]
Apologies. Can you try again with https://github.com/gndean/home-assistant-hypervolt-charger/releases/tag/v1.2.3 ?

**Comment by stoogie** [comment]
> Apologies. Can you try again with https://github.com/gndean/home-assistant-hypervolt-charger/releases/tag/v1.2.3 ?

That appears to have solved it. Thank you.

**Comment by rockclimb** [comment]
Yep, looks great, thanks. I'm successfully using it with an Integration helper to feed my energy dashboard.
