### ISSUE TITLE
Plugged v Unplugged

### ISSUE THREAD

**Issue by GPDixon** [gndean/home-assistant-hypervolt-charger#35]
It would be really great if the integration told you if the charger was plugged into the car at any point in time. The mobile app shows a status of Unplugged. Any chance you could implement this as a binary switch please?
The reason for this request is to do with Session Energy (and your Total Session Energy extension). Neither seem to work as I hoped. Having spoken to Hypervolt Support, my understanding is that the Session Energy value should be treated as a ever increasing value and should only be 'reset' once the vehicle has been unplugged/re-plugged. Hence I should/could ignore any spurious resets until I see its been unplugged....if I knew when that was!

**Comment by gndean** [comment]
With the Hypervolt 2.0 at least, it's not possible to know when the car is plugged in; only when its charging. I'm not sure if that's the still the case with Hypervolt 3.0 devices.

https://github.com/gndean/home-assistant-hypervolt-charger/issues/36 tracks a similar request so I'm going to close this one and keep #36 open.
