### ISSUE TITLE
Charger readiness monitoring

### ISSUE THREAD

**Issue by CodedCarbon** [gndean/home-assistant-hypervolt-charger#36]
Hello, Thank you for a great integration!
Is it possible to make the readiness state a condition for monitoring in automations?.
It would also be good if it is possible to toggle the "switch" to change the state to "Ready" if the state is not ready.

**Comment by dandwhelan** [comment]
I think you're describing something I'm after. I need a way to monitor when the hypervolt has been plugged into the car.

**Comment by gndean** [comment]
I have a Hypervolt 2.0 and there doesn't appear to be a way to tell when the car is plugged in or not. Not sure if this is possible with a Hypervolt 3.0 unit. Does your Hypervolt app show whether the car is plugged in or not?

**Comment by CodedCarbon** [comment]
I've figured a way using the action in an automation to "Toggle Hypervolt Charging" I use this for when the vehicle is charging or I change the state by activating actions based on conditions or triggers or I want to change the "charge mode option" as the new Hypervolt app now no longer lets you change the charge type whilst charging.
