### ISSUE TITLE
Activation Mode doesn't update

### ISSUE THREAD

**Issue by Meatballs1** [gndean/home-assistant-hypervolt-charger#4]
Changing the activation mode in the app, the new value isn't reflected in home assistant. Everything else seems to update instantly.

**Comment by Meatballs1** [comment]
Looking at your demo it doesn't look like the app updates either to reflect the new value. Its not part of the websocket comms which would explain it.

Also just spotted it in the readme so nevermind

**Comment by gndean** [comment]
Yeah, it should update within 5 minutes, as that's how often the integration polls. I'm not sure of a better solution. I wouldn't want to poll more frequently and hammer the Hypervolt APIs.
