### ISSUE TITLE
Hypervolt new update - Schedules not syncing now

### ISSUE THREAD

**Issue by prestonsmartuk** [gndean/home-assistant-hypervolt-charger#42]
Hi,

Looks like Hypervolt have pushed a new update recently (ios in my case). It's changed the way the scheduling is done; with each session now able to specify the days it's workable on. This update hasnow broken the syncing of the scheduling between the the app and Home Assistant.

**Comment by gndean** [comment]
Thanks for reporting.

This should be fixed in V2.0.2 now
