### ISSUE TITLE
Feature Request: Car Plugged in Yes/No for use in automations

### ISSUE THREAD

**Issue by lasagne1989** [gndean/home-assistant-hypervolt-charger#43]
Entity to show whether a car is plugged in or not for use in automations (help me stop forgetting to switch to Plug and Charge).

**Comment by gndean** [comment]
Yes, this looks to be possible. I'll add this shortly.

**Comment by gndean** [comment]
I've just created a V2.2.0 Beta that includes a new sensor: Car Plugged 🎉 

You'll need to enable Beta downloads within HACS to get it but please give it a try and report back here if it works for you.

I'm especially keen to know if it works with V2 chargers.

**Comment by github-dpmracing** [comment]
Thanks for the swift tweak.  I’ve got v2.2.0-beta running on my latest code HA instance.  It’s shows the new binary sensor “ binary_sensor.hypervolt_car_plugged” however it remains “off” even when I’ve attached a car. 

This is on a v2 charger running pi4.202209271128.1962865

looks like HV still aren’t auto updating charger firmware as that looks suspiciously like 18 month old firmware, if it’s of any benefit I can give Hv support a call tomorrow and ask them to update it

**Comment by gndean** [comment]
@github-dpmracing Does your Hypervolt app show the plugged state? With a HV 3 charger, the app shows a picture of a car behind the charger if the car is plugged in, otherwise a plug.

![image](https://github.com/gndean/home-assistant-hypervolt-charger/assets/18371246/70217813-f6a8-43e0-931e-0ded49f0a4f5) vs 
![image](https://github.com/gndean/home-assistant-hypervolt-charger/assets/18371246/bb976527-046e-49a9-ac07-3c7bc59f83eb)
(ignore the colour differences)

**Comment by github-dpmracing** [comment]
The car only appears behind the charger when a charging session is in progress.

for instance I set plug&charge but with solar boost so it didn’t actually start a session and no car appears (see below)

![IMG_1399](https://github.com/gndean/home-assistant-hypervolt-charger/assets/141822709/656b8400-65f6-400d-a819-c0f11b819c82)

**Comment by github-dpmracing** [comment]
I’ve just checked with HV and pi4.202209271128.1962865 is the latest version of firmware

**Comment by lasagne1989** [comment]
@gndean works perfectly on my v3.0. Thanks for adding the feature. Let me know if you want anymore info/testing

**Comment by ashleycbaker** [comment]
I have tested with my v2 charger too and the sensor remains "unplugged" regardless. My firmware version is 202112220802.523dc30

**Comment by ashleycbaker** [comment]
I got HV support to upgrade my firmware this evening, it's now on 202209271157.345295f. 

What I did notice last night was the entity did switch over to plugged in only for the period in which the scheduled charge occured 00:30 -> 04:30 then switched back, even though the car was connected for ~12hr.

I will see if anything changes with the updated firmware over the next few days

**Comment by gndean** [comment]
OK, thanks for the feedback. It looks like the plugged status is only supported by V3 devices.
I'll only expose the new Plugged sensor for V3 devices then. Sorry V2 owners!

**Comment by gndean** [comment]
This is released in 2.2.2 now.
