### ISSUE TITLE
Hypervolt 3.0 CT clamp reports wrong data after session end

### ISSUE THREAD

**Issue by ptashek** [gndean/home-assistant-hypervolt-charger#45]
First of all, thank you for this integration. It was one of the reasons why I got a Hypervolt.

My device is a "Hypervolt Home Charger 3.0" with firmware 2627.0

On several occasions I have noticed that the reported CT clamp power value drops, as expected, at the end of a charging session, only to go back up - as if the car was still charging - a second later. The value is then misreported for almost the exact same duration as the original charging session.

In the attached screenshot you can observe what this looks like.
The actual session starts at 2am and ends at 6:30am, charging a 6.6kW
The reported value drops to 580W (base load) at 6:30:01am and goes back up to base load + 6.6kW a second later and continues like this until shortly after 11am.

As I'm not sure what could be the source of this issue, I have reported this to Hypervolt support as well, but might be worth investigating if this could be related to the integration.

<img width="1642" alt="Screenshot 2024-03-11 at 23 25 19" src="https://github.com/gndean/home-assistant-hypervolt-charger/assets/2490317/2daacac4-5d19-48d5-a8a6-27fae2db1d2a">

**Comment by ptashek** [comment]
Integration: v1.3.1 

Home Assistant:
- Core: 2024.3.0
- Supervisor: 2024.02.1
- Operating System: 12.0
- Frontend: 20240306.0

**Comment by ptashek** [comment]
@gndean I did more testing today, and I'm reasonably confident this is something in the integration code. 

As my session was coming to an end, I've watched the Hypervolt Android app to check if the data remains misreported there as well. And it was reported correctly as soon as the session ended.

The HS entity displayed the tell-tale 1s blip at the end of the session, and then the data was misreported for the exact same length of time as the session itself. 

I have a workaround in place, where I have a secondary entity that tracks the last charge session's average voltage and current, and then subtracts the power value from the reported CT clamp value if no charge session is in progress. 

I'll try and check if I can debug this further at code level.

Here's an overlay of correct/incorrect data:
<img width="1041" alt="Screenshot 2024-04-12 at 17 04 55" src="https://github.com/gndean/home-assistant-hypervolt-charger/assets/2490317/94f1db44-2a83-48f3-ab39-3f0659e20a2b">

And the blip:
<img width="1029" alt="Screenshot 2024-04-12 at 17 08 42" src="https://github.com/gndean/home-assistant-hypervolt-charger/assets/2490317/4dfbc315-8b54-492b-b2da-c009a5aaa5d1">

**Comment by gndean** [comment]
Thanks for the issue report.

The `CT Power` sensor is just a report of a raw field from the Hypervolt APIs. There is no processing that the integration does with it.
Since I moved from a HV 2.0 charger to a HV 3.0 charger, I no longer see this field populated at all, whereas it was with my HV 2.0 charger.
I suspect its meaning has changed internally within the HV API spec. But that's just a guess.

I appreciate your report and investigation however I am going to close this as a "won't fix" because the integration is just reporting what the HV servers supply and without any documentation, I'm not confident to make any further inferences to its precise meaning.

**Comment by ptashek** [comment]
OK, understood. 

On my HV3 charger the CT clamp data is used internally to grid load balance, and - assuming it's installed as per manual - reports the full house load, which enables the charger to manage the different boost and eco modes appropriately, especially if there's other heavy loads active during the charge session, or PV production.

Interesting that you say this data is not populated with your charger at all. Firmware differences?
Mine's at 2627.0

**Comment by RGx01** [comment]
I have a similar issue. But not sure if it's a problem with the charger firmware or integration. When my charge session ends, grid power remains at the session end power and house power jumps to the grid power value. The curious thing is... it's like Schrödinger's API, as soon as you look it returns to normal... I'm just not sure if it was opening the hypervolt app or opening home assistant  that triggers the values to return. It happens at leat once a month and very frustrating. 
<img width="1245" alt="Screenshot 2024-04-19 at 06 19 15" src="https://github.com/gndean/home-assistant-hypervolt-charger/assets/149301136/04ccdd44-a4c1-45e8-a5cb-6e013c0c7a94">

**Comment by ptashek** [comment]
@RGx01 If it helps, I have worked around this with the sensor config below. It's far from ideal, but has been reasonably accurate.

```
- name: "EV Charger CT Power Corrected"
      unique_id: ev_charger_ct_power_corrected
      state_class: measurement
      unit_of_measurement: W
      device_class: power
      state: >
        {% if (states("switch.hypervolt_charging") == "on") %}
          {{ states("sensor.hypervolt_grid_power") | float(default=0) }}
        {% else %}
          {% set power = states("sensor.hypervolt_grid_power") | float(default=0)  %}
          {% set avg_session_current = states("sensor.ev_charger_session_current") | float(default=0) %}
          {% set avg_session_voltage = states("sensor.ev_charger_session_voltage") | float(default=0) %}
          {% set avg_session_power = avg_session_current * avg_session_voltage %}
          {% if (avg_session_power > 0  and power > avg_session_power) %}
            {{ power - avg_session_power }}
          {% else %}
            {{ power }}
          {% endif %}
        {% endif %}
    - name: "EV Charger Session Voltage"
      unique_id: ev_charger_session_voltage
      state_class: measurement
      unit_of_measurement: V
      device_class: voltage
      state: >
        {% set last_voltage = states("sensor.ev_charger_session_voltage") | float(default=0) %}
        {% if (states("switch.hypervolt_charging") == "on") %}
          {% set voltage = states("sensor.hypervolt_voltage") | float(default=0) %}
          {{ voltage if last_voltage == 0 else ((voltage + last_voltage)/2) }}
        {% else %}
          {{ last_voltage }}
        {% endif %}
    - name: "EV Charger Session Current"
      unique_id: ev_charger_session_current
      state_class: measurement
      unit_of_measurement: A
      device_class: current
      state: >
        {% set last_current = states("sensor.ev_charger_session_current") | float(default=0) %}
        {% if (states("switch.hypervolt_charging") == "on") %}
          {% set current = states("sensor.hypervolt_charger_current") | float(default=0) %}
          {{ current if last_current == 0 else ((current + last_current)/2) }}
        {% else %}
          {{ last_current }}
        {% endif %}
```

**Comment by RGx01** [comment]
Thanks @ptashek I'll give it try and see what happens when it occurs again.

**Comment by RGx01** [comment]
Happened again @ptashek. Observed the same behaviour of opening the Hypervolt app and it suddenly showing the correct values in HA. I was using your sensor config with a small modification to only correct power when the avg_session_power > 50 rather than 0. But I think my logic was flawed and it didn't catch it so again the stats are messed up. Frustrating.

I'm changing it for a Zappi because next month for other reasons (energy supplier integration) so hopefully I don't see the issue again.
