### ISSUE TITLE
Can CT power entity always be available

### ISSUE THREAD

**Issue by jacippet** [gndean/home-assistant-hypervolt-charger#49]
Is there any way to always have the CT power entity always producing data as opposed to only when the charging session is ongoing? Other than that thanks for all your work on this.

**Comment by Meatballs1** [comment]
I doubt it unless HV open up a local API - they won't want constant CT power data ramping up their cloud bills

**Comment by ptashek** [comment]
My Hypervolt 3 is reporting CT power data 24/7 with a 10s resolution, and this data is also displayed live in their Android app's main screen.

**Comment by RGx01** [comment]
@jacippet try Hypervolt grid power. I recently updated to latest release (2.1) and found the Hypervolt CT power only reports during charge.

**Comment by gndean** [comment]
As @RGx01 says, this should now be resolved with the addition of the Grid Power sensor in V2.1.0 of the integration. For HV 3.0 units, this reports regularly, even when not charging.
