### ISSUE TITLE
Authentication error when trying to log in, status code: 400

### ISSUE THREAD

**Issue by Paul-G-M** [gndean/home-assistant-hypervolt-charger#50]
I've had a replacement Hypervolt charger (v2 > v3), therefore needed to update this integration. Also took the opportunity to strengthen my password. Removed the v2 charger from the Integration and put in my updated credentials > authentication error. Decided to completely remove the Hypervolt integration > reboot HA > re-downloaded & installed integration > re-booted HA.  Still got authentication error when submitting my email and password (which work just fine on the Hypervolt web dashboard & smartphone app). What am I missing?

Log info:
   This error originated from a custom integration.

   Logger: custom_components.hypervolt_charger.hypervolt_api_client
   Source: custom_components/hypervolt_charger/hypervolt_api_client.py:111
   integration: Hypervolt Charger (documentation, issues)
   First occurred: 22:56:32 (1 occurrences)
   Last logged: 22:56:32

   Authentication error when trying to log in, status code: 400

Many thanks, :)

**Comment by nathbooth** [comment]
Same issue for me, wondering if Hypervolt have changed something.  
`This error originated from a custom integration.

Logger: custom_components.hypervolt_charger.hypervolt_api_client
Source: custom_components/hypervolt_charger/hypervolt_api_client.py:111
integration: Hypervolt Charger (documentation, issues)
First occurred: 09:23:46 (2 occurrences)
Last logged: 10:24:53

Authentication error when trying to log in, status code: 400` 
Which is a bad request, so implies something is being rejected.

**Comment by gndean** [comment]
Very strange. I can't repeat this issue. Are you still seeing the same error?

As it happens, I've released a beta version of the integration that uses a whole different way to log in. You could always try that. You'll need to enable/show beta versions within HACS. It's 2.0.0 Beta.

**Comment by Paul-G-M** [comment]
Beta version 2.0.1 installed. Still get Authentication error. Could it be to do with my password? It contains ! @ and ^ symbols. 14 characters in total. I tried changing the password to remove these characters and it still failed. :(

**Comment by nathbooth** [comment]
i had special characters too, however i've removed them all and still the issue persists with the 400 errors. Any tips on debugging further?

**Comment by benjumanji** [comment]
@nathbooth and @Paul-G-M can you login using the same credentials using the app?

**Comment by Paul-G-M** [comment]
If you mean the Hypervolt app, then yes. Not tried the HA app, but can do if required.Thanks for not giving up on this.Best,PaulPaul Mellor07980 017089Sent from my mobile. Please excuse brevity and typosOn 12 Apr 2024, at 17:35, Benjamin Edwards ***@***.***> wrote:﻿
@nathbooth and @Paul-G-M can you login using the same credentials using the app?

**Comment by benjumanji** [comment]
Hi yes, I did mean the hypervolt mobile app, I just wanted to check you weren't having a problem with the new infra. Please note you've just dropped your mobile phone number on a public forum, I'd nuke that pronto. I'm assuming @gndean that the new credentials grant is working for you?

**Comment by Paul-G-M** [comment]
Oops - thx!Paul MellorSent from my mobile. Please excuse brevity and typosOn 12 Apr 2024, at 18:05, Benjamin Edwards ***@***.***> wrote:﻿
Hi yes, I did mean the hypervolt mobile app, I just wanted to check you weren't having a problem with the new infra. Please note @Paul-G-M you've just dropped your mobile phone number on a public forum, I'd nuke that pronto. I'm assuming @gndean that the new credentials grant is working for you?

**Comment by gndean** [comment]
> I'm assuming @gndean that the new credentials grant is working for you?
Sorry for the silence on this - I've been busy for the last couple of weeks.
I've not tried this yet but will do so this weekend and get it merged assuming no problems found, so we can see if that fixes this issue.

**Comment by gndean** [comment]
@benjumanji The new credentials grant isn't working - see [PR](https://github.com/gndean/home-assistant-hypervolt-charger/pull/48) for details.

Sorry, I've no idea what's happening here. For what it's worth, I don't think it's an issue with your password format as I've tested with a pw of 50 characters, including symbols .
@Paul-G-M with the 2.0.1 beta integration, is it still as 400 error specifically you see? That's the HV servers saying it's a bad request, opposed to wrong credentials, say.

**Comment by gndean** [comment]
@Paul-G-M , @nathbooth can you please try V2.0.2 beta when you have chance. This now authenticates via Hypervolt's new auth infrastructure.

**Comment by bobbyeo** [comment]
i was having same issue, i just tested v2.0.2 and it's working now, thanks.

**Comment by Paul-G-M** [comment]
It works with Beta v2.02! Huge thanks for sorting this.PaulSent from my mobile. Please excuse brevity and typosOn 13 Apr 2024, at 15:37, gndean ***@***.***> wrote:﻿
@Paul-G-M , @nathbooth can you please try V2.0.2 beta when you have chance. This now authenticates via Hypervolt's new auth infrastructure.

**Comment by gndean** [comment]
Excellent, thanks for the feedback.

Released as V2.0.2 now
