### ISSUE TITLE
CT power entity no longer reports data in v2.0.2

### ISSUE THREAD

**Issue by ptashek** [gndean/home-assistant-hypervolt-charger#52]
After updating from v1.3.1 to v2.0.2 the CT clamp power entity - **sensor.hypervolt_ct_power** - is no longer receiving any data, and has an "unknown" state. Confirmed by downgrading to v1.3.1, which again started populating the live data. 

Hypervolt 3.0

**Comment by gndean** [comment]
Sorry for missing this and thanks for reporting it so quickly.

The raw value: ct_power is no longer reported from the new HV APIs that this integration and the app uses. However, I've made some changes within V2.1.0 Beta of the integration:
* Attempting to reproduce the CT Power by deriving it from the CT current and Voltage
* Added new sensors: EV Power, House Power, Grid Power and Generation Power

Give it a try and see what you think.

**Comment by ptashek** [comment]
Will definitely give the beta a try and report back. Thank you!

You mention `ct_power is no longer reported from the new HV APIs` - this caught my interest as the HV app v5.3.1 on Android still reports this data live, with an approx. 10s refresh interval. This is my only point of reference for comparison. I wonder if this is still using what would classify as "old" API then?

**Comment by ptashek** [comment]
Moved to beta 2.1, and can report the power data is being reported again and in line with what the mobile app shows. 
Thank you!

**Comment by gndean** [comment]
> Will definitely give the beta a try and report back. Thank you!
> 
> You mention `ct_power is no longer reported from the new HV APIs` - this caught my interest as the HV app v5.3.1 on Android still reports this data live, with an approx. 10s refresh interval. This is my only point of reference for comparison. I wonder if this is still using what would classify as "old" API then?

The kW value shown below the image of the charger? I think this is coming from the EV Power value that's now exposed via a new sensor in the integration. You might find this is a better reflection of the charging power, compared to the CT Power. It certainly seems to be in my brief testing.

**Comment by ptashek** [comment]
Yes, the three kW values shown on the grid, house and solar icons.
