### ISSUE TITLE
How can I unpause when charger becomes paused?

### ISSUE THREAD

**Issue by boncey** [gndean/home-assistant-hypervolt-charger#55]
Hello, first off just want to say that I find this automation to be really useful so thanks for all your work on it.

I'm trying to resolve an issue where my charger is somehow ending up as "paused" which causes my car to not charge.
I have a Hypervolt 3.0 and Octopus Energy Intelligent Go (which controls the car). I use a HA automation to unlock the charger when the car is plugged in and off peak rates apply. 

This has worked fine for months but in the last month or so I've sometimes woken up to an uncharged car. After lots of digging I've worked out that the charger was unlocked but showing as "paused" in the iPhone app. This status seems to match "Hypervolt Charging Readiness" = "Not Ready - Force Stopped" in HA.
After more digging I've worked out that this happens when my automation tells the charger to unlock _when it's already unlocked_. This seems to be triggering pause mode.

I've now updated my automation to not tell it to unlock if it's already unlocked. But my car is charged now so I can't really test any of this for a few days.

Hopefully the above resolves the issue but I'd like to get a better understanding of this paused mode. Is there an entity to track it and/or a command to unpause that I can add to my automations as a belt and braces measure?

Thanks in advance.
Darren.

**Comment by benjumanji** [comment]
This doesn't sound right. Locking and pausing are two different actions. If you aren't explicitly asking the charger to pause it should never show up as paused in the phone app.

(not a developer on this project, employee of hypervolt, own views disclaimer blah blah)

**Comment by pastyface** [comment]
Hi, I have a similar issue - my automation successfully pauses charging (using Turn off Hypervolt Charging) and it goes into Force Stopped, but recently it's not been unpausing (with Turn on Hypervolt Charging) so I have to go to the hypervolt app and tap the unpause button there.

Is there anything I can do to see why it's failing?

Thanks,
Dewi

**Comment by gndean** [comment]
Apologies for not responding sooner. The lock feature in the HA integration just sends the lock/unlock command to the HV APIs. I don't think there's anything else the HA integration can do here.

If we wanted to dig into this further, you could try repeating the issue while capturing debug logs from HA and sharing them here.  Feel free to reopen the issue but I'm going to close it now

**Comment by boncey** [comment]
Thanks for responding @gndean (and @benjumanji) . As mentioned I changed my automation and I've been unable to replicate it since then.

Thanks,
Darren.
