### ISSUE TITLE
No reconnect following connection error(s)

### ISSUE THREAD

**Issue by johnbradshw** [gndean/home-assistant-hypervolt-charger#57]
2.2.5 with HV v3

Car didn't charge overnight following connection error to HV yesterday afternoon, which has left the connection closed. A reload of the Hypervolt integration has established connection again.

![Screenshot_20240616_071905_Home Assistant.jpg](https://github.com/gndean/home-assistant-hypervolt-charger/assets/29913166/da5c7568-3b71-4fb9-9a75-868ed56ef7b2)

![Screenshot_20240616_071918_Home Assistant.jpg](https://github.com/gndean/home-assistant-hypervolt-charger/assets/29913166/8f401234-fe8f-4dec-914c-d3920ecf80e3)

**Comment by gndean** [comment]
Thanks for the report. Please try the latest release: V2.2.6 and see if this fixes the issue.
