### ISSUE TITLE
Issues since 2024.7

### ISSUE THREAD

**Issue by JohnnyKipper** [gndean/home-assistant-hypervolt-charger#64]
issues since upgrading to 2024.7

This error originated from a custom integration.

Logger: custom_components.hypervolt_charger
Source: custom_components/hypervolt_charger/__init__.py:72
integration: Hypervolt Charger (documentation, issues)
First occurred: 20:49:17 (23 occurrences)
Last logged: 21:13:23

Async_setup_entry exception:

**Comment by gndean** [comment]
I think this is the same issue as #62, which hopefully should be closed now, so closing as a duplicate. Please re-open or comment if not.

**Comment by JohnnyKipper** [comment]
All good, working again.  Top man….
