### ISSUE TITLE
Missed commands 

### ISSUE THREAD

**Issue by burden42** [gndean/home-assistant-hypervolt-charger#65]
Having issues where Frist set of instructions from a automation , does not always take . 

Have now adapted my automations to check for change of state on hypervolt . That or run a second automation a few minutes latter

**Comment by ejellard** [comment]
I'm getting this too - switches aren't changing state, but do a few hours later when the automation runs again.

**Comment by gndean** [comment]
OK, I can repeat this too and think I understand what's happening: I think the token associated with the websocket connection used to make these changes is invalid after 1 hour and the integration currently only discovers this after trying to communicate on it (by sending a command). This then causes a connection error and forces the websocket to reconnect, meaning that the next command (so long as it's within an hour) succeeds.

I'll look into fixing this by tearing down the reconnecting the websocket before the token expires.

**Comment by liquidfusionv** [comment]
I know this is a bit old but I noticed this issue aswell, hoping you find a fix else I'll have to issue repeat command every 59 minutes to keep it alive lol

**Comment by RedNo7** [comment]
Same problem here - been happening for a while now but assumed it was just me.

I sometimes have to 'press' my switch 10 times for it to take and my automations nearly always fail now (as they try only once) so i'm having to redo them to keep trying until successful (which isn't great).

**Comment by liquidfusionv** [comment]
What I've done is do my automation, then have it wait 5 minutes, then repeat the same commands again to ensure it goes through.

**Comment by RedNo7** [comment]
I use a 'while loop' up to 10 times - although today its has been working well (1st attempt every time).  Happy to share the code if you are interested.

**Comment by liquidfusionv** [comment]
All good, it usually works on the second attempt if it fails the first.

**Comment by gndean** [comment]
I've created a beta release: V2.3.5 Beta which I'm hoping will help with this issue.
Please give it a try when you have chance and report back.

**Comment by RedNo7** [comment]
v3.2.5. beta installed.  Will watch over a couple of days and report back!

**Comment by chrisbtmn** [comment]
I had the same problem and V2.3.5 Beta has fixed it. A couple of automations that used to fail regularly both worked today. Thanks 🙂

**Comment by gndean** [comment]
Thanks @chrisbtmn. Anyone else have any feedback?

**Comment by liquidfusionv** [comment]
Apologies, I haven't had a chance to charge the car however playing around with the LED brightness it seems to take first time, so can assume it's fixed. Good job

**Comment by RedNo7** [comment]
much better for me!

**Comment by gndean** [comment]
Phew, thanks for the feedback. I've released this now (exactly the same as the beta).
