### ISSUE TITLE
Boost, Eco & Super Eco

### ISSUE THREAD

**Issue by boab21mac** [gndean/home-assistant-hypervolt-charger#67]
Would appease these options don't work. When running an automation during sunny days to use Suoer Eco and start charge. system won't charge, due to command to change cycle not being actioned. 

Power options when selected don't update at hypervolta end.

**Comment by gndean** [comment]
I suspect this might be the same as #65. Could you confirm if retrying the action after a few seconds works? I'm not suggesting this is a fix, I'm just trying to work out if the symptoms are the same as #65

**Comment by gndean** [comment]
Assuming this is fixed with #65
