### ISSUE TITLE
Sensor value sensor.hypervolt_ct_power reads high

### ISSUE THREAD

**Issue by petheridge** [gndean/home-assistant-hypervolt-charger#7]
I have a live readout of our smart meter, the ct_power reading appears about 20% higher than the meter. Taking the sensor.hypervolt_ct_current and the sensor.hypervolt_voltage values and multiplying does give an accurate power reading for the ct clamp location. My guess is there could be a factor at safety included in the ct_power value?![image](https://user-images.githubusercontent.com/30731128/209306648-e8fc038d-275a-4b0b-9fc9-c8ec09535a58.jpeg)

**Comment by andykorol1** [comment]
I believe this is the CT of total load on your house rather than just the charger. The CT clamp it is using is next to your main incoming supply to sees any load. It is like this to do with load balancing. Cheers

**Comment by petheridge** [comment]
Apologies, I don't think I explained very clearly. So the bottom sensor in the screenshot 'Instant Electricity' is a live readout from our meter (Hilderbrand zigbee Glowstick). Reading 7998w for the whole house, the Hypervolt CT Power is showing 9743w.
However if you multiply the CT current by voltage (34.74A x 233V) = 8094W, much closer to the true reading at the meter.

**Comment by gndean** [comment]
Thanks for the feedback. The CT Power values comes from the Hypervolt APIs and this integration just reporting the values seen.
For what it's worth, based on last night's charge, my CT Power was reading about 14% higher than the power reported by my SolarEdge modbus meter. But if I multiply my Hypervolt CT current by Hypervolt voltage, that gives me a figure that's 10% _higher_ again. So my figures are different to yours and no doubt many others'.
If you get consistent over-reading, you could create a new template sensor in Home Assistant that compensates. Or similarly create a template sensor for the product of the current and voltage. But I don't think there's a better solution for this Home Assistant integration other than to report the values as-is.
I will add something to the next release's readme to caveat these sensors saying that the values are provided as-is and just report what the Hypervolt APIs return.
I suggest we close this ticket, unless you think there's more that could be done?

**Comment by petheridge** [comment]
Thanks for getting back to me and for all your hard work on the integration. Agree, best to close this issue and just add a note to the readme.

**Comment by exalyte** [comment]
So had to wait until charge time rolled around but ive just tested mine
using my Octopus inhouse monitor 

IHD 7.15KWH
HyperVolt Integration 
![image](https://user-images.githubusercontent.com/73583564/209415293-25b9c6aa-cf4d-4b34-aba4-aa06cd687b0a.png)


HyperVolt shouldnt really push beyond 7kw so i wouldnt expect to see much more than 7kwh on the charger CT ever 
Is it possible your CT Clamps were installed incorrectly? you should have 2 (3 if using solar) one in INSIDE the charger its smaller maybe 1.5cm wide 
the other is the standard CT clamp style and will probably go to your meter tail (thats where mine goes at least) 


###### 7 minuets later ##########
![image](https://user-images.githubusercontent.com/73583564/209415487-40b1ef26-9dd2-482d-94c8-88c3ae0f6175.png)

**Comment by Meatballs1** [comment]
In previous discussions on the Facebook group HV have said the CT data reported is raw from the metering chip and isn't correctly normalised for use (and that it wouldnt be much good for anyone).

I (think) I use the true milliamps reading multiplied by the voltage in a template in powercalc and that mostly matches the sessions data reported in the app.

**Comment by gndean** [comment]
I've added a note to the V1.0.5 readme caveating the values from this sensor. Closing issue now.
