### ISSUE TITLE
Not working with V2.0

### ISSUE THREAD

**Issue by Meatballs1** [gndean/home-assistant-hypervolt-charger#70]
I don't seem to be getting any updates through for my v2 unit for a few days now and can't control it via the integration.

I can't troubleshoot it at the moment but wondering if anyone else has the same issue?

Seems to have stopped working after the 19th

**Comment by exalyte** [comment]
This is a hypervolt issue
Give them a call they can't fix it but they are taking notes of how many are impacted. 

The app I assume also shows zero data when charging?

**Comment by Meatballs1** [comment]
Seems to be back up and running as of last.night
