### ISSUE TITLE
EV power entity not working

### ISSUE THREAD

**Issue by Rlwhittle** [gndean/home-assistant-hypervolt-charger#73]
I swapped over to use the EV power entity recently and all was working fine. Now for the past couple of weeks it doesn't display anything (hypervolt 2.0 if that helps). 

I can use ct power but it doesn't report anything meaningful - home assistant does report that the car is charging though.

**Comment by melvanderwal** [comment]
This one is a Hypervolt API issue. If you look at the Hypervolt app, it has the same problem with 0 kW reported. 
![Screenshot_20240909-084743](https://github.com/user-attachments/assets/44731b9d-deb6-4ee4-8fa3-531d8cfdf83f)

I raised it with Hypervolt support, and I suggest that you do as well so they expedite a fix. The last response that I received was:
> We have escalated this directly with our engineering team.

> We are currently still working on identifying the root cause of the problem, however I do understand the impact this has on your experience. In the mean time, we are getting ready to the release of the v6 app version wich should eliminate many of these new processing errors.

**Comment by Rlwhittle** [comment]
Thanks for the response - will raise it with hypervolt as well

**Comment by melvanderwal** [comment]
Also a heads-up to @gndean that it sounds like they're releasing a new version of the app shortly, which might mean backend API changes too.

**Comment by gndean** [comment]
Closing as not a HA issue.
Thanks for the heads up. Yeah, I look forward to another rework!

**Comment by melvanderwal** [comment]
Received an email from Hypervolt that apparently it's been fixed. I'm currently travelling overseas and will be for the next month so I can't test to confirm, but maybe @Rlwhittle can?
