### ISSUE TITLE
Session money spent appears wrong

### ISSUE THREAD

**Issue by andykorol1** [gndean/home-assistant-hypervolt-charger#8]
The value in session money spent seems to be calculated at 14p per kWh rather than what is set in my Hypervolt tariff settings. The value on the Hypervolt website is also incorrect(same as this integration) but the app is showing the correct value. I think is issue is at Hypervolts end but wondered if this could grab the data the app is seeing?

**Comment by gndean** [comment]
Thanks for the feedback. Yeah, it is wrong but used to be what the app reported, so the integration just reports the same. With the recent app update, there's now a new tariff-respecting calculation included in the analytics section.

When I get chance, I'll see if there's any way the integration could support this so I'll keep the issue open. In the meantime, I'll consider dropping this sensor from the next release as it's probably of no practical use.

**Comment by gndean** [comment]
V1.0.5 has dropped the Session Money Spent sensor. The Readme lists that the lack of money tracking is a known issue.

I intend to look at supporting the new tariff-aware calculations but that will be a future feature so I'll close this ticket now.
